### ISSUE TITLE
Does not open on arc browser.

### ISSUE THREAD

**Issue by Pasithea0** [JoacoEsteban/vind#3]
I have reinstalled it several times, but it still does nothing when I tap the extension icon. If I right-click, I can go to the settings page.

**Comment by JoacoEsteban** [comment]
Hey, thanks for trying Vind!
That's weird, I also used Arc.
Have you refreshed the tab (where you want to use Vind) after installing the extension? That's the main factor for the popup to not appear (also a browser restart will work).
Also may I ask on which website are you trying it on? So I can try replicating it myself.

**Comment by Pasithea0** [comment]
Oh hmm, it's working now. I restarted Arc a few times and it worked after the second restart. Strange

**Comment by JoacoEsteban** [comment]
Glad to hear! I'll close this issue then. Feel free to open another one if you have more questions.
